### ISSUE TITLE
App only uploading photos for the first time install and not for the second time

### ISSUE THREAD

**Issue by lalthomas** [devedup/FlickrKit#29]
Hi David,

Thank you for your great library. I tested the demo app and found that it can only upload the photo only for the first time. The next time it is crashing.

**Comment by devedup** [comment]
Thanks for the info. It’s only a demo, to demonstrate the usage, so it’s not that important, but I’ll look into it anyway in case it’s a bug in the library.

Thanks for letting me know.

David

**Comment by lalthomas** [comment]
@devedup I'm debugging the project right now and found that `[info objectForKey:UIImagePickerControllerReferenceURL]` is returning null. This stackoverflow [question](http://stackoverflow.com/q/27496888/2182047) is having the same issue. As per one of the answer this seems to be fixed for the xcode 8.2.x versions. I am currently using  8.1.
