### ISSUE TITLE
Default Account

### ISSUE THREAD

**Issue by bport95** [devedup/FlickrKit#34]
Hello, I am wondering if there is a way to login automatically so that the username and password would be hardcoded into the app and it would be used as a way for the user to upload photos without them having to have a Flickr account?

**Comment by devedup** [comment]
Possibly, yes. You could store user/password and generate a token. See checkAuthorizationOnCompletion and the demo app. It's probably in your Flickr terms that you're not allowed to share your account or something like that though. If your token/session expired you wouldn't ever want to present the Flickr login web view, so best to look into under what circumstances that might happen.

**Comment by devedup** [comment]
Also, you're better off asking questions like this on Stackoverflow with a bigger audience.
