### ISSUE TITLE
Response is very slow

### ISSUE THREAD

**Issue by kevinlieser** [devedup/FlickrKit#41]
Hi @devedup and thanks for your great FlickrKit!

There is one question after testing FlickrKit: Is just the Flickr API so slow or is it the Library? Re-Auth, takes approx. 4 - 5 seconds. Loading PhotoSets takes 10 seconds or something. Is this "normal"? Is just the FlickrAPI so heavy slow? If so there is no way to produce an App with nice usability AND Flickr integration.

Thanks for your feedback!

**Comment by devedup** [comment]
Come on... as if a piece of code takes 10 seconds to run, especially something as simple as this. 

The problem was likely Flickr servers or your network connection.
