### ISSUE TITLE
Using swift 2.0 on ios 9.2 facing Error as bellow

### ISSUE THREAD

**Issue by Mahadev77** [devedup/FlickrKit#46]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FlickrKit", referenced from:
      type metadata accessor for __ObjC.FlickrKit in HomeViewController.o
ld: symbol(s) not found for architecture x86_64

**Comment by devedup** [comment]
This sounds more like a problem with your project setup than a problem with FlickrKit. Have a look at StackOverflow for similar problems: http://stackoverflow.com/questions/18408531/xcode-build-failure-undefined-symbols-for-architecture-x86-64

Also, Swift is at 3.0 now, or you can use Swift 2.3.

**Comment by Mahadev77** [comment]
Thank you for your reply, Documentation of FlickrKit is not good enough to
understand for new people like me. Please guide me which is header to
import in Project-bridge-Header? There is no framework to add only folder
named class, so difficult to understand it. used pod install so can you
please help me to solve it?


Thank You,
Mahadev

**Comment by devedup** [comment]
Hi Again,

I give CocoaPod installation and Manual installation instructions. I also provide two sample projects, one in ObjectiveC and one in Swift. I would hardly say my instruction were not good enough.

A projects installation instructions are a guidance and not meant to be a tutorial on how to integrate frameworks. You should look to CocoaPods or other web articles for help and use StackOverflow, where I'm sure there would be lots of willing people with time to help you with your problem, which doesn't seem to be an isolated case of installing FlickrKit, but that you are having trouble integrating frameworks in general. 

David

**Comment by devedup** [comment]
... and regarding your specific problem, it would be hard for me to determine what the problem was with what information you have provided. CocoaPods 'pod install' should setup and link to the frameworks correctly. You would then 'import FlickrKit' in the top of the swift file in which you want to use it.
