### ISSUE TITLE
1.0.9 not available in cocoapods

### ISSUE THREAD

**Issue by karlbecker** [devedup/FlickrKit#51]
I imagine 1.0.9 is not available on cocoapods because the tests are failing according to the badge on the README of this repo. However, the sample code is for the 1.0.9 API, since it uses the `photoArray` property, which is not available in 1.0.8.

So two things:

1. Could we upgrade cocoapods to 1.0.9 so we can put `pod 'FlickrKit', '~> 1.0.9'` into our podfile ?
2. If the new `photoArray` property is the preferred way to fetch the results, should it be bumped up to 1.1 since the sample code is not backward compatible with 1.0.8?

Also, if I can help get a test passing to get 1.0.9 ready for cocoapods, let me know.

Thanks!

**Comment by karlbecker** [comment]
Note: for anyone else looking for a solution to not yet being able to use 1.0.9, do this in your pod file:
```
pod 'FlickrKit', :git => 'https://github.com/devedup/FlickrKit'
```

That works fine - it'll just be a little slicker to have 1.0.9 be available from the master pod repo.

**Comment by devedup** [comment]
I'm having a look now. I'll put it in the master repo.

**Comment by devedup** [comment]
Done.
