### ISSUE TITLE
No such module 'FlickerKit'

### ISSUE THREAD

**Issue by DipakBCS** [devedup/FlickrKit#55]
Hello 
I am using Swift 3.0  and Xcode 8.3.2
I have tried to install flicke, via cocoa pods, installation was successful.
I am not able to access any files of Flicker framework.

I have tried with following lines.
*FlickrKit.sharedFlickrKit().initializeWithAPIKey("", sharedSecret: "")*
and it gives me error *No such module 'FlickerKit'*
Please help me to solve this issue.
I also tried with to set *FrameworkSearch Path* and *UserHeaderSearchPath*, but It couldn't solve the error.
Please give me your answer ASAP.
*Thanks In Advance*

**Comment by devedup** [comment]
Did you import at the top of your Swift file?

import FlickrKitFramework

**Comment by devedup** [comment]
I just imported FlickrKit into my current project successfully via CocoaPods:

import FlickrKit

FlickrKit.shared().initialize(withAPIKey: "", sharedSecret: "")

This sounds like a problem with your project setup and cocoa pods installation, not a problem with FlickrKit. You should seek help on StackOverflow.
